name: starport_template
description: Starport template for flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: 2.0.5
  uuid: 3.0.5
  http: 0.13.4
  decimal: 1.5.0
  flutter_mobx: 2.0.2
  modal_bottom_sheet: 2.0.0
  qr_flutter: 4.0.0
  clipboard: 0.1.3
  share_plus: 3.0.4
  intl: 0.17.0
  cosmos_ui_components:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_ui_components
      ref: main

  cosmos_utils:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_utils
      ref: main

  transaction_signing_gateway:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/transaction_signing_gateway
      ref: main

  cupertino_icons: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.1
  flutter_launcher_icons: 0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon/app_icon.png"

## convenient overrides for development to reference packages on local disk, just uncomment following lines and make sure
## it points to the location of the checked out tendermint/flutter repository
#dependency_overrides:
#  cosmos_utils:
#    path: ../packages/cosmos_utils
#  transaction_signing_gateway:
#    path: ../packages/transaction_signing_gateway
#  cosmos_ui_components:
#    path: ../packages/cosmos_ui_components

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: packages/cosmos_ui_components/fonts/Inter-Thin.ttf
          weight: 100
        - asset: packages/cosmos_ui_components/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: packages/cosmos_ui_components/fonts/Inter-Light.ttf
          weight: 300
        - asset: packages/cosmos_ui_components/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/cosmos_ui_components/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/cosmos_ui_components/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/cosmos_ui_components/fonts/Inter-Bold.ttf
          weight: 700
        - asset: packages/cosmos_ui_components/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: packages/cosmos_ui_components/fonts/Inter-Black.ttf
          weight: 900