name: cosmos_utils
description: Common utils package
version: 0.0.1
homepage: starport.com

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  intl: ^0.17.0
  bip39: ^1.0.6
  bech32: ^0.2.1
  hex: ^0.2.0
  equatable: ^2.0.3
  package_info: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.8.1

flutter:
