include: package:cosmos_lint/analysis_options.yaml
analyzer:
  exclude:
    - build/**
    - lib/proto/**
    - lib/**/*.g.dart
    - lib/**/*.reflectable.dart

    - test/**/*.g.dart
    - test/**/*.reflectable.dart

    - tool/**/*.g.dart
  strong-mode:
    implicit-casts: false

  # enable-experiment:
  #  - non-nullable

linter:
  rules:
    - camel_case_types