name: cosmos_node_client
description: cosmos node client package
version: 0.0.1
publish_to: 'none'
homepage: starport.com

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bech32: 0.2.1
  bip39: 1.0.6
  equatable: 2.0.3
  dartz: 0.10.1
  pointycastle: 3.6.0
  hex: 0.2.0
  cosmos_utils:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_utils
      ref: main

## convenient overrides for development to reference packages on local disk, just uncomment following lines and make sure
## it points to the location of the checked out tendermint/flutter repository
#dependency_overrides:
#  cosmos_utils:
#    path: ../cosmos_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosmos_lint:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_lint
      ref: main

  mocktail: 0.3.0

flutter:
